version: '3.8'

services:
  backup-control-system:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src/uploads:/app/src/uploads
      - ./src/reports:/app/src/reports
      - ./src/database:/app/src/database
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/config"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

